"use client";

import { createContext, useContext, useEffect, useMemo, useState } from "react";

type Language = "en" | "bn";

type LanguageContextValue = {
  language: Language;
  setLanguage: (language: Language) => void;
  toggleLanguage: () => void;
  t: (key: string) => string;
};

const translations: Record<Language, Record<string, string>> = {
  en: {
    "nav.haircare": "Haircare",
    "nav.careGuide": "Care Guide",
    "nav.hairOils": "Hair Oils",
    "nav.packages": "Packages",
    "nav.track": "Track My Order",
    "nav.refer": "Refer & Win",
    "nav.findCare": "Find Your Care",
    "nav.hairOil": "Hair Oil",
    "nav.hairToner": "Hair Toner",
    "nav.shampoo": "Shampoo",
    "nav.allHaircare": "All Haircare",
    "nav.hairFall": "Hair Fall",
    "nav.dryHair": "Dry Hair",
    "nav.scalpCare": "Scalp Care",
    "header.customerCare": "Customer Care",
    "header.findUs": "Find us on",
    "header.search": "Search",
    "header.openCart": "Open cart",
    "hero.kicker": "ALVERO HAIR SOLUTIONS",
    "hero.title": "Nature-led care for",
    "hero.italic": "stronger, healthier hair.",
    "hero.copy": "Effective, high-quality hair solutions designed to restore confidence and enhance your natural beauty.",
    "hero.shop": "Shop haircare",
    "hero.stories": "See customer stories",
    "hero.carefully": "carefully considered",
    "hero.every": "every bottle",
    "hero.across": "across Bangladesh",
    "home.essentials": "Your everyday essentials",
    "home.mustHave": "Must-Have For You",
    "home.mustHaveDesc": "Simple, nature-inspired products for the hair care ritual you can keep coming back to.",
    "home.viewHaircare": "View all haircare",
    "home.complete": "Complete care, beautifully bundled",
    "home.rituals": "Exclusive Hair Care Rituals",
    "home.ritualsDesc": "Everything you need to nourish, cleanse and refresh — together in one considered routine.",
    "home.explorePackages": "Explore packages",
    "home.approach": "The Alvero approach",
    "home.bannerTitle": "Healthy hair begins with the",
    "home.bannerItalic": "right care.",
    "home.bannerCopy": "Build a ritual that feels as good as it looks. Start with one essential or choose the complete three-step routine.",
    "home.shopRitual": "Shop the complete ritual",
    "home.personalised": "Personalised care",
    "home.findRitual": "Find the right ritual for your hair",
    "home.findRitualDesc": "Choose what your hair needs today and discover a few thoughtful places to start.",
    "home.exploreAll": "Explore all haircare",
    "home.realStories": "Real stories, real rituals",
    "home.testimonials": "Testimonials — What Our Customers Say",
    "home.testimonialsDesc": "A thoughtful routine is personal. Here are a few demo customer stories for the Alvero experience.",
    "home.softer": "Softer-feeling hair",
    "home.calmer": "A calmer routine",
    "home.shopRitualShort": "Shop the ritual",
    "home.watchStories": "Watch care stories",
    "home.realRoutines": "Real routines, real confidence",
    "home.ourCustomers": "What our customers say",
    "home.seeAllStories": "See all customer stories",
    "home.madeFor": "Made for your ritual",
    "home.careLooks": "Care that looks as good as it feels",
    "home.careLooksDesc": "A closer look at the botanical world behind the Alvero experience.",
    "product.add": "Add to cart",
    "product.soldOut": "Sold out",
    "product.quickAdd": "Quick add",
    "product.saleEnds": "Sale ends in",
    "product.limited": "Limited offer",
    "product.buyNow": "Buy now",
    "product.cash": "Cash on Delivery",
    "product.quality": "Quality checked",
    "product.support": "Easy support",
    "product.description": "Description",
    "product.complete": "Complete your ritual",
    "product.youLike": "You may also like",
    "product.viewAll": "View all",
    "product.customerReviews": "Customer Reviews",
    "product.realStories": "Real stories from the ritual",
    "product.writeReview": "Write a review",
    "cart.ritual": "Your ritual",
    "cart.title": "Shopping Cart",
    "cart.emptyTitle": "Your cart is waiting",
    "cart.emptyCopy": "Add a care essential and build your Alvero ritual.",
    "cart.shopHaircare": "Shop haircare",
    "cart.subtotal": "Subtotal",
    "cart.checkout": "Go to checkout",
    "cart.mayLike": "You may also like",
    "cart.quickAdd": "Quick add",
    "collection.browse": "Browse by",
    "collection.essentials": "care essentials, curated for your ritual",
    "collection.allHaircare": "All Haircare",
    "collection.help": "Need help choosing?",
    "collection.start": "Start with our complete three-step ritual.",
    "collection.explore": "Explore packages",
    "footer.shop": "Shop",
    "footer.help": "Help",
    "footer.promise": "Our promise",
    "footer.call": "Call us",
    "footer.email": "Email",
    "footer.find": "Find us",
    "footer.demo": "Demo customer stories",
    "footer.created": "Created by",
    "footer.nature": "Nature-inspired care",
    "footer.delivery": "Delivery across Bangladesh",
    "footer.quality": "Quality-first packaging",
    "footer.support": "Support when you need it",
    "checkout.almost": "Almost there",
    "checkout.shipping": "Shipping details",
    "checkout.name": "Your name",
    "checkout.phone": "Phone number",
    "checkout.address": "Shipping address",
    "checkout.cash": "Cash on Delivery",
    "checkout.cashCopy": "Pay when your Alvero order arrives.",
    "checkout.place": "Place order (Cash on Delivery)",
    "checkout.summary": "Order summary",
    "checkout.items": "item",
    "checkout.empty": "Your cart is empty.",
    "checkout.fast": "Fast delivery",
    "checkout.secure": "Secure checkout",
    "checkout.thoughtful": "Thoughtful care",
    "track.kicker": "Order care",
    "track.title": "Where’s my order?",
    "track.copy": "Enter your details and we’ll help you find it instantly.",
    "track.track": "Track my order",
    "track.demo": "Thanks — this demo tracker is ready to connect to your order system.",
    "refer.kicker": "Refer & win",
    "refer.title": "Share care. Get rewarded.",
    "refer.copy": "Pass a thoughtful hair ritual forward and enjoy a little thank-you from Alvero.",
    "refer.start": "Get started",
    "guide.kicker": "The Alvero journal",
    "guide.title": "Hair Care Guide",
    "guide.subtitle": "Real, simple hair-care tips — চুলের যত্নের সহজ গাইড।",
    "guide.desc": "Small, practical habits for a healthier-looking hair care routine.",
    "guide.read": "Read guide",
    "guide.back": "Back to Care Guide",
    "guide.faq": "Common questions",
    "guide.faqDesc": "A few simple answers before you begin your next ritual.",
    "guide.en": "English",
    "guide.bn": "বাংলা",
    "guide.next": "Next guide",
    "guide.previous": "Previous guide"
  },
  bn: {
    "nav.haircare": "চুলের যত্ন",
    "nav.careGuide": "কেয়ার গাইড",
    "nav.hairOils": "হেয়ার অয়েল",
    "nav.packages": "প্যাকেজ",
    "nav.track": "অর্ডার ট্র্যাক করুন",
    "nav.refer": "রেফার & জিতুন",
    "nav.findCare": "আপনার যত্ন বেছে নিন",
    "nav.hairOil": "হেয়ার অয়েল",
    "nav.hairToner": "হেয়ার টোনার",
    "nav.shampoo": "শ্যাম্পু",
    "nav.allHaircare": "সব হেয়ার কেয়ার",
    "nav.hairFall": "চুল পড়া",
    "nav.dryHair": "শুষ্ক চুল",
    "nav.scalpCare": "স্ক্যাল্প কেয়ার",
    "header.customerCare": "কাস্টমার কেয়ার",
    "header.findUs": "আমাদের খুঁজুন",
    "header.search": "সার্চ",
    "header.openCart": "কার্ট খুলুন",
    "hero.kicker": "ALVERO হেয়ার সলিউশনস",
    "hero.title": "প্রকৃতির যত্নে",
    "hero.italic": "আরও শক্ত, স্বাস্থ্যকর চুল।",
    "hero.copy": "আপনার প্রাকৃতিক সৌন্দর্য ও আত্মবিশ্বাস ফিরিয়ে আনতে কার্যকর, উচ্চমানের হেয়ার কেয়ার সমাধান।",
    "hero.shop": "হেয়ার কেয়ার কিনুন",
    "hero.stories": "কাস্টমার স্টোরি দেখুন",
    "hero.carefully": "যত্ন নিয়ে তৈরি",
    "hero.every": "প্রতিটি বোতলে",
    "hero.across": "বাংলাদেশজুড়ে",
    "home.essentials": "প্রতিদিনের প্রয়োজনীয়তা",
    "home.mustHave": "আপনার জন্য অবশ্যই দরকারি",
    "home.mustHaveDesc": "সহজ, প্রকৃতি-অনুপ্রাণিত পণ্য—যে হেয়ার কেয়ার রুটিনে বারবার ফিরে আসতে ভালো লাগবে।",
    "home.viewHaircare": "সব হেয়ার কেয়ার দেখুন",
    "home.complete": "সুন্দরভাবে সাজানো সম্পূর্ণ যত্ন",
    "home.rituals": "এক্সক্লুসিভ হেয়ার কেয়ার রিচুয়াল",
    "home.ritualsDesc": "পুষ্টি, পরিষ্কার ও সতেজতার জন্য দরকারি সবকিছু—একটি সহজ রুটিনে।",
    "home.explorePackages": "প্যাকেজ দেখুন",
    "home.approach": "Alvero-এর পদ্ধতি",
    "home.bannerTitle": "স্বাস্থ্যকর চুল শুরু হয়",
    "home.bannerItalic": "সঠিক যত্ন থেকে।",
    "home.bannerCopy": "দেখতে সুন্দর এবং ব্যবহারেও সহজ একটি রুটিন তৈরি করুন। একটি পণ্য দিয়ে শুরু করুন অথবা সম্পূর্ণ তিন ধাপের রুটিন বেছে নিন।",
    "home.shopRitual": "সম্পূর্ণ রুটিন কিনুন",
    "home.personalised": "ব্যক্তিগত যত্ন",
    "home.findRitual": "আপনার চুলের জন্য সঠিক রুটিন",
    "home.findRitualDesc": "আজ আপনার চুলের কী প্রয়োজন বেছে নিন এবং যত্ন শুরু করার সহজ উপায় খুঁজে নিন।",
    "home.exploreAll": "সব হেয়ার কেয়ার দেখুন",
    "home.realStories": "বাস্তব গল্প, বাস্তব যত্ন",
    "home.testimonials": "কাস্টমাররা কী বলছেন",
    "home.testimonialsDesc": "একটি ভালো রুটিন ব্যক্তিগত। Alvero অভিজ্ঞতার কিছু ডেমো কাস্টমার স্টোরি এখানে দেখুন।",
    "home.softer": "আরও নরম অনুভূতি",
    "home.calmer": "আরও সহজ রুটিন",
    "home.shopRitualShort": "রুটিন কিনুন",
    "home.watchStories": "কেয়ার স্টোরি দেখুন",
    "home.realRoutines": "বাস্তব রুটিন, বাস্তব আত্মবিশ্বাস",
    "home.ourCustomers": "কাস্টমারদের কথা",
    "home.seeAllStories": "সব কাস্টমার স্টোরি",
    "home.madeFor": "আপনার রুটিনের জন্য",
    "home.careLooks": "যত্ন, যা দেখতে ও অনুভবে সুন্দর",
    "home.careLooksDesc": "Alvero অভিজ্ঞতার পেছনে থাকা প্রকৃতি-অনুপ্রাণিত জগতের কাছ থেকে আরও একটু দেখুন।",
    "product.add": "কার্টে যোগ করুন",
    "product.soldOut": "স্টক শেষ",
    "product.quickAdd": "দ্রুত যোগ করুন",
    "product.saleEnds": "অফার শেষ হবে",
    "product.limited": "সীমিত অফার",
    "product.buyNow": "এখনই কিনুন",
    "product.cash": "ক্যাশ অন ডেলিভারি",
    "product.quality": "কোয়ালিটি চেকড",
    "product.support": "সহজ সাপোর্ট",
    "product.description": "বিবরণ",
    "product.complete": "আপনার রুটিন সম্পূর্ণ করুন",
    "product.youLike": "আপনার আরও পছন্দ হতে পারে",
    "product.viewAll": "সব দেখুন",
    "product.customerReviews": "কাস্টমার রিভিউ",
    "product.realStories": "রুটিনের বাস্তব গল্প",
    "product.writeReview": "রিভিউ লিখুন",
    "cart.ritual": "আপনার রুটিন",
    "cart.title": "শপিং কার্ট",
    "cart.emptyTitle": "আপনার কার্ট অপেক্ষায়",
    "cart.emptyCopy": "একটি কেয়ার এসেনশিয়াল যোগ করে Alvero রুটিন তৈরি করুন।",
    "cart.shopHaircare": "হেয়ার কেয়ার কিনুন",
    "cart.subtotal": "সাবটোটাল",
    "cart.checkout": "চেকআউটে যান",
    "cart.mayLike": "আপনার আরও পছন্দ হতে পারে",
    "cart.quickAdd": "দ্রুত যোগ করুন",
    "collection.browse": "ব্রাউজ করুন",
    "collection.essentials": "আপনার রুটিনের জন্য বাছাই করা পণ্য",
    "collection.allHaircare": "সব হেয়ার কেয়ার",
    "collection.help": "বাছাই করতে সাহায্য দরকার?",
    "collection.start": "আমাদের সম্পূর্ণ তিন ধাপের রুটিন দিয়ে শুরু করুন।",
    "collection.explore": "প্যাকেজ দেখুন",
    "footer.shop": "শপ",
    "footer.help": "সাহায্য",
    "footer.promise": "আমাদের প্রতিশ্রুতি",
    "footer.call": "ফোন করুন",
    "footer.email": "ইমেইল",
    "footer.find": "ঠিকানা",
    "footer.demo": "ডেমো কাস্টমার স্টোরি",
    "footer.created": "তৈরি করেছেন",
    "footer.nature": "প্রকৃতি-অনুপ্রাণিত যত্ন",
    "footer.delivery": "বাংলাদেশজুড়ে ডেলিভারি",
    "footer.quality": "কোয়ালিটি প্যাকেজিং",
    "footer.support": "প্রয়োজনে সাপোর্ট",
    "checkout.almost": "প্রায় শেষ",
    "checkout.shipping": "শিপিং তথ্য",
    "checkout.name": "আপনার নাম",
    "checkout.phone": "ফোন নম্বর",
    "checkout.address": "শিপিং ঠিকানা",
    "checkout.cash": "ক্যাশ অন ডেলিভারি",
    "checkout.cashCopy": "Alvero অর্ডার পৌঁছালে পেমেন্ট করুন।",
    "checkout.place": "অর্ডার করুন (ক্যাশ অন ডেলিভারি)",
    "checkout.summary": "অর্ডার সামারি",
    "checkout.items": "টি পণ্য",
    "checkout.empty": "আপনার কার্ট খালি।",
    "checkout.fast": "দ্রুত ডেলিভারি",
    "checkout.secure": "নিরাপদ চেকআউট",
    "checkout.thoughtful": "ভালোবাসার যত্ন",
    "track.kicker": "অর্ডার কেয়ার",
    "track.title": "আমার অর্ডার কোথায়?",
    "track.copy": "আপনার তথ্য দিন, আমরা দ্রুত অর্ডার খুঁজে দিতে সাহায্য করব।",
    "track.track": "অর্ডার ট্র্যাক করুন",
    "track.demo": "ধন্যবাদ — এই ডেমো ট্র্যাকারটি আপনার অর্ডার সিস্টেমের সঙ্গে যুক্ত করার জন্য প্রস্তুত।",
    "refer.kicker": "রেফার & জিতুন",
    "refer.title": "যত্ন শেয়ার করুন, পুরস্কার জিতুন।",
    "refer.copy": "একজন বন্ধুর সঙ্গে Alvero রুটিন শেয়ার করুন এবং আমাদের পক্ষ থেকে ধন্যবাদ উপহার পান।",
    "refer.start": "শুরু করুন",
    "guide.kicker": "Alvero জার্নাল",
    "guide.title": "হেয়ার কেয়ার গাইড",
    "guide.subtitle": "Real, simple hair-care tips — চুলের যত্নের সহজ গাইড।",
    "guide.desc": "স্বাস্থ্যকর চুলের জন্য ছোট, বাস্তব ও সহজ কিছু অভ্যাস।",
    "guide.read": "গাইড পড়ুন",
    "guide.back": "কেয়ার গাইডে ফিরুন",
    "guide.faq": "সাধারণ প্রশ্ন",
    "guide.faqDesc": "আপনার পরবর্তী রুটিন শুরু করার আগে কয়েকটি সহজ উত্তর।",
    "guide.en": "English",
    "guide.bn": "বাংলা",
    "guide.next": "পরের গাইড",
    "guide.previous": "আগের গাইড"
  }
};

const LanguageContext = createContext<LanguageContextValue | null>(null);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>("en");

  useEffect(() => {
    const saved = window.localStorage.getItem("alvero-language");
    if (saved === "bn" || saved === "en") setLanguageState(saved);
  }, []);

  useEffect(() => {
    document.documentElement.dataset.lang = language;
    window.localStorage.setItem("alvero-language", language);
  }, [language]);

  const value = useMemo<LanguageContextValue>(() => ({
    language,
    setLanguage: (next) => setLanguageState(next),
    toggleLanguage: () => setLanguageState((current) => current === "en" ? "bn" : "en"),
    t: (key) => translations[language][key] ?? translations.en[key] ?? key
  }), [language]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) throw new Error("useLanguage must be used inside LanguageProvider");
  return context;
}

export function LanguageToggle({ compact = false }: { compact?: boolean }) {
  const { language, setLanguage, t } = useLanguage();
  return <div className={`language-toggle ${compact ? "language-toggle-compact" : ""}`} aria-label="Choose language"><button type="button" className={language === "en" ? "active" : ""} onClick={() => setLanguage("en")}>{compact ? "EN" : t("guide.en")}</button><span>/</span><button type="button" className={language === "bn" ? "active" : ""} onClick={() => setLanguage("bn")}>{compact ? "বাংলা" : t("guide.bn")}</button></div>;
}
